import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyRuntimeProvider } from "./MyRuntimeProvider";

import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full">
			<body className={cn(inter.className, "h-full")}>
				<MyRuntimeProvider>{children}</MyRuntimeProvider>
			</body>
		</html>
	);
}
